version: '3.8'
services:
  db:
    image: mysql:8.2.0
    volumes:
      - ./docker/db/data:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    restart: always
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PMA_EXPOSE_PORT}:80
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    volumes:
      - .:/app:cached
      - golang:/go
    ports:
      - ${APP_EXPOSE_PORT}:${APP_PORT}
    depends_on:
      - db
volumes:
  mysql_data:
  golang:
