version: '3.8'
services:
  db:
    image: mysql:8.2.0
    volumes:
      - ./docker/db/data:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    env_file:
      - .env.local
    ports:
      - 13306:3306
    restart: always
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    env_file:
      - .env.local
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app:cached
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  mysql_data:
