version: '3'
tasks:
  build:
    desc: Build the executable file
    deps:
      - download
      - generate
    cmds:
      - go build -o bin/main main.go
  download:
    desc: Download dependencies
    cmds:
      - go mod tidy
      - go mod download
      - go mod verify
  generate:
    desc: Code generate
    cmds:
      - echo "Code generation"
  ci:
    desc: Run continuous integration commands
    deps:
      - fmt
      - lint
      - unit
      - vuln
  fmt:
    desc: Format the packages
    deps:
      - install_fmt
    cmds:
      - goimports -w .
  install-fmt:
    internal: true
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
    status:
      - ( ! type goimports )
  lint:
    desc: Lint the packages
    deps:
      - install_lint
    cmds:
      - golangci-lint run ./...
  install-lint:
    internal: true
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - ( ! type golangci-lint )
  vuln:
    desc: Check vulnerabilities
    deps:
      - install_vuln
    cmds:
      - govulncheck ./...
  install-vuln:
    internal: true
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
    status:
      - ( ! type govulncheck )
  test:
    desc: Run the unit tests
    cmds:
      - go test -v ./...
  test-all:
    desc: Run the unit and e2e tests
    deps:
      - test
      - test:e2e
  test-e2e:
    desc: Run the e2e tests
    dotenv:
      - .env.local
    deps:
      - install_e2e
    cmds:
      - docker compose up -d
      - until curl http://localhost:8080 -o /dev/null; do sleep 1; done
      - scenarigo run --config ./e2e/config.yaml
      - docker compose stop
  install-e2e:
    internal: true
    cmds:
      - go install github.com/zoncoen/scenarigo/cmd/scenarigo@latest
    status:
      - ( ! type scenarigo )
  docker-up:
    desc: Run docker compose up
    dotenv:
      - .env.local
    cmds:
      - docker compose up
  docker-down:
    desc: Run docker compose down
    cmds:
      - docker compose down
  docker-buildup:
    desc: Run docker compose build and up
    dotenv:
      - .env.local
    cmds:
      - docker compose up --build
  docker-build:
    desc: Run docker compose build
    dotenv:
      - .env.local
    cmds:
      - docker compose build
  docker-debug:
    desc: Run docker include sql client
    dotenv:
      - .env.local
    cmds:
      - docker compose --profile debug up
  run:
    desc: Run the main.go
    dotenv:
      - .env.local
    cmds:
      - go run -v main.go
  run-hotload:
    desc: Hot reload
    dotenv:
      - .env.local
    deps:
      - install_hotloader
      - build
    cmds:
      - air -c .air.toml
  install-hotloader:
    desc: Install hot reloader
    internal: true
    cmds:
      - go install github.com/cosmtrek/air@latest
    status:
      - ( ! type air )
  update:
    desc: Update dependencies
    cmds:
      - go get -u
  clean:
    desc: Remove output files and clean cache
    cmds:
      - rm -rf bin/main
      - go clean
  coverage:
    desc: Test-coverage displays code coverage per package
    deps:
      - coverage_html
    cmds:
      - go tool cover -func cover.out
  coverage_html:
    desc: Generate HTML coverage report
    internal: true
    cmds:
      - go test -race -timeout 30m -cover ./... -coverprofile=cover.out
      - go tool cover -html=cover.out -o cover.html
