name: Go vulnerability check
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/govuln.yaml
      - '**.go'
      - go.mod
      - go.sum
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/govuln.yaml
      - '**.go'
      - go.mod
      - go.sum
    types:
      - labeled
      - opened
  schedule:
    # JST 09:00
    - cron: '0 0 * * *'
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run govulncheck
        run: govulncheck -C . ./...
        shell: bash
