name: Vulnerability
env:
  IMAGE: built_image
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/vulncheck.yaml
      - '**.go'
      - go.mod
      - go.sum
      - Dockerfile
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/govuln.yaml
      - '**.go'
      - go.mod
      - go.sum
      - Dockerfile
    types:
      - labeled
  schedule:
    # JST 09:00
    - cron: '0 0 * * *'
jobs:
  remove_label:
    runs-on: ubuntu-latest
    if: "((github.event.action == 'labeled') && (github.event.label.name == 'Vulncheck'))"
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Remove label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: "Vulncheck"
            }
            await github.rest.issues.removeLabel(params)
  govulncheck:
    runs-on: ubuntu-latest
    if: "((github.event.action == 'labeled') && (github.event.label.name == 'Vulncheck')) || (github.event_name == 'push') || (github.event_name == 'schedule')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run govulncheck
        run: govulncheck -C . ./...
        shell: bash
  dockle_trivy_job:
    runs-on: ubuntu-latest
    if: "((github.event.action == 'labeled') && (github.event.label.name == 'Vulncheck')) || (github.event_name == 'push') || (github.event_name == 'schedule')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: |
          docker build -t "${{ env.IMAGE }}:${{ github.sha }}" .
      - name: Run dockle scanner
        uses: goodwithtech/dockle-action@main
        with:
          image: "${{ env.IMAGE }}:${{github.sha }}"
          format: 'list'
          exit-code: '1'
          exit-level: 'warn'
          ignore: 'CIS-DI-0001,DKL-DI-0006'
      - name: Run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE }}:${{ github.sha }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
